name: DOC

on:
  push:
    branches: [ gh-pages ]
  

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3
        pip install -r requirements.txt
        pip install wheel; python setup.py sdist bdist_wheel
    - name: Setup pages
      env: 
        PYTHONWARNINGS: error::UserWarning
      run: |
        pdoc --html FuncNotify --force
        touch html/FuncNotify/.nojekyll
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: html/FuncNotify #
        
        
        