name: DOC

on:
  push:
    branches: [ gh-pages ]
  release:
    types: [ created ]
  

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3
        pip install -r requirements.txt
    - name: Build pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: html/FuncNotify #
      run: |
        pip install wheel; python setup.py sdist bdist_wheel
        pdoc --html FuncNotify --force
        
        